### ISSUE TITLE
Expected identifier in jmorecfg.h

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#1]
```
In file included from assemble.c:14:
In file included from headers\jpegHeaders/jpeglib.h:27:
headers\jpegHeaders/jmorecfg.h:263:17: error: expected identifier
 typedef enum { FALSE = 0, TRUE = 1 } boolean;
                ^
headers\AR/ar.h:104:17: note: expanded from macro 'FALSE'
#  define FALSE 0
                ^
In file included from assemble.c:14:
In file included from headers\jpegHeaders/jpeglib.h:27:
headers\jpegHeaders/jmorecfg.h:263:28: error: expected identifier
 typedef enum { FALSE = 0, TRUE = 1 } boolean;
                           ^
headers\AR/ar.h:101:16: note: expanded from macro 'TRUE'
#  define TRUE 1
```

**Comment by kalwalt** [comment]
Hi @Carnaux can you share your build emcc command maybe this error dipend on how you linked and added the includes, to build with node.js the jsartoolkit5 lib this is my setup:

```js
// Lib JPEG Compilation

// Memory Allocations
// jmemansi.c jmemname.c jmemnobs.c jmemdos.c jmemmac.c
var libjpeg_sources = 'jcapimin.c jcapistd.c jccoefct.c jccolor.c jcdctmgr.c jchuff.c \
		jcinit.c jcmainct.c jcmarker.c jcmaster.c jcomapi.c jcparam.c \
		jcphuff.c jcprepct.c jcsample.c jctrans.c jdapimin.c jdapistd.c \
		jdatadst.c jdatasrc.c jdcoefct.c jdcolor.c jddctmgr.c jdhuff.c \
		jdinput.c jdmainct.c jdmarker.c jdmaster.c jdmerge.c jdphuff.c \
		jdpostct.c jdsample.c jdtrans.c jerror.c jfdctflt.c jfdctfst.c \
		jfdctint.c jidctflt.c jidctfst.c jidctint.c jidctred.c jquant1.c \
		jquant2.c jutils.c jmemmgr.c \
		jmemansi.c'.split(/\s+/).join(' /home/walter/kalwalt-github/jsartoolkit5/emscripten/jpeg-6b/')
function clean_builds() {
	try {
		var stats = fs.statSync(OUTPUT_PATH);
	} catch (e) {
		fs.mkdirSync(OUTPUT_PATH);
	}

```
https://github.com/kalwalt/jsartoolkit5/blob/master/tools/makem.js

i hope that this can help you!

**Comment by Carnaux** [comment]
I copied the folders with the headers and sources and i'm using just the necessary to build the genTexData.c and replaced the jpeglib.h with the one from https://github.com/LuaDist/libjpeg/blob/master/jpeglib.h, and now i'm getting "undefined symbol" with the functions from jpeglib, for example the `jpeg_stdio_dest`, i think it is a linking error.

**Comment by kalwalt** [comment]
I think you should use the jpeg-6b version from http://libjpeg.sourceforge.net/

**Comment by Carnaux** [comment]
@kalwalt i can't get it to work, can you try it? The assemble.c is in the dev branch, the source codes for building are in the artoolkit master, in the folders include and lib.

**Comment by kalwalt** [comment]
i will try it :smile:

**Comment by kalwalt** [comment]
I' m working on it, i think maybe tomorrow i have something to show to you... :smile:

**Comment by kalwalt** [comment]
I had a failure of my hard disk, i had to re-install my system and i lost my work on `NFT-marker-Creator` :sob:  I have ot re-done everything. But note this libjpeg version is important, there are small changes in the different versions, I collect the file i used in this repo: https://github.com/kalwalt/libjpeg-for-jsartoolkit5
also other important thing to use the artoolkit5 from https://github.com/artoolkitx/artoolkit5
tested commit : https://github.com/artoolkitx/artoolkit5/tree/6742d9f5c4a06673a3805e097d924f8e0c55f8ca
at least that was used to build jsartoolkit5.

**Comment by Carnaux** [comment]
> I had a failure of my hard disk, i had to re-install my system and i lost my work on NFT-marker-Creator 😭 I have to re-done everything. 

😭😭😭😭

Thanks for your help, i will do some tests!!
