### ISSUE TITLE
TypeError: Cannot read property 'value' of undefined

### ISSUE THREAD

**Issue by AnastasiiaaaaM** [Carnaux/NFT-Marker-Creator#10]
Hi there!

I'm getting the error "Cannot read property 'value' of undefined" when running ' node app.js'.

**Comment by pepperface** [comment]
Me too. Any advice and/or info will be eagerly awaited and very gratefully received when it comes :)

**Comment by kalwalt** [comment]
Hi @AnastasiiaaaaM @pepperface  i tested right now for me it output the files:

```shell
walter@walter-RC530-RC730:~/kalwalt-github/NFT-Marker-Creator$ npm install
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN nodegenerator@1.0.0 No repository field.

added 14 packages from 6 contributors and audited 17 packages in 5.619s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

walter@walter-RC530-RC730:~/kalwalt-github/NFT-Marker-Creator$ node app.js
[info] Name = [info] first = 28
[info] Filename: asa
[info] --
Generator started at 2019-12-12 15:46:45 +0100
[info] MAX_THRESH  = 0.900000
[info] MIN_THRESH  = 0.550000
[info] SD_THRESH   = 8.000000
[info] SURF_FEATURE = 100
[info]  min allow 3.762000.
[info] Image DPI (1): 3.762000
[info] Image DPI (2): 4.739823
[info] Image DPI (3): 5.971803
[info] Image DPI (4): 7.524000
[info] Image DPI (5): 9.479647
[info] Image DPI (6): 11.943607
[info] Image DPI (7): 15.048002
[info] Image DPI (8): 18.959294
[info] Image DPI (9): 23.887215
[info] Image DPI (10): 30.096005
[info] Image DPI (11): 37.918591
[info] Image DPI (12): 47.774432
[info] Image DPI (13): 60.192014
[info] Image DPI (14): 75.837187
[info] Image DPI (15): 95.548870
[info] Image DPI (16): 120.384034
[info] Image DPI (17): 151.674382
[info] Image DPI (18): 191.097750
[info] Image DPI (19): 220.000000
[info] Generating ImageSet...
[info]    (Source image xsize=1637, ysize=2048, channels=3, dpi=220.0).
[info]   Done.
[info] Saving to asa.iset...
[info]   Done.
[info] Generating FeatureList...
[info] Start for 220.000000 dpi image.
[info] p: 5308272
[info]          ImageSize = 3352576[pixel]
[info] Extracted features =  760859[pixel]
[info]  Filtered features =   67388[pixel]
2047/2048.[info] 
[info]   Done.
[info] Max feature = 3444
```

Maybe a node issue? Which version are you using?
my is:

```shell
walter@walter-RC530-RC730:~/kalwalt-github/NFT-Marker-Creator$ node -v
v13.2.0


```

**Comment by Carnaux** [comment]
It looks like it is the EXIF reader, can you copy the log?

**Comment by kalwalt** [comment]
> It looks like it is the EXIF reader, can you copy the log?

Are you asking to me? what log?

**Comment by Carnaux** [comment]
Sorry, to @AnastasiiaaaaM and @pepperface

**Comment by Carnaux** [comment]
Done, some properties that I was reading may not exist in the EXIF of some images, so it was getting undefined. Now I added user input if it doesn't find those properties, and I added a new dependency, so you need to update yours. Tell me if it works and I will close this issue.

**Comment by pepperface** [comment]
Hi @kalwalt ... and many thanks for your time. It genuinely is much appreciated :) 

In answer to your question, I'm running v8.9.4.

**Comment by kalwalt** [comment]
@pepperface you are welcome! if you have other issues open another one, we will try to help as much possible...

**Comment by t2elzeth** [comment]
Hi there. I got the same error while trying to create NFT markers using node app.

Here is the entire folder I was working with: (More info such as steps I had done before getting error in README.md file in repo)
`https://github.com/t2elzeth/nft-marker-creator`
