### ISSUE TITLE
Some restrictions about input files

### ISSUE THREAD

**Issue by nicolocarpignoli** [Carnaux/NFT-Marker-Creator#11]
Hi,

My idea is, with this issue, to try to list all input images requirements and known problems.
**Not all of the following have to be fixed: some of them may become requirements, other may be bugs to fix.**

Known requirements/limitations:

- file has to have .jpg extension
- file name has to contain .jpg extension (e.g. on Mac verify that extension is present)
- after resizing the image (e.g. Using Mac OS Preview tool) the system gives an error
- I have used a black and white image, set NC=1, but does not work (generates .iset files but not recognised). Someone can try this too? Maybe can be something on the NFT app side, maybe missing some parameters.

Other?

**Comment by nicolocarpignoli** [comment]
Also I have found this and put it on jsartoolkit5 repo: https://github.com/kalwalt/jsartoolkit5/blob/fixing-nft/doc/NFT_image_constraints.md

it says:

# NFT Image Constraints

ARToolKit NFT is able to recognize and track natural features of photos and documents, specifically, **planar textured surfaces**. However, to accomplish this, ARToolKit NFT requires that the visual appearance of the surface is known in advance. Thus, the system has to be trained with a surface in advance to recognize and track the surface.

The output of this training is a set of data that can be used for realtime tracking in application using the ARToolKit SDK.


The following constraints apply to surfaces which can be used with ARToolKit NFT.

* The surfaces to be tracked must be supplied as a rectangular image
* The images must be supplied in jpeg format
* The surface must be textured and have a reasonable amount of fine detail and sharp edges (a low degree of self-similarity and high spatial-frequency). Images with large areas of single flat color, that are blurred or have soft detail will not track well, if at all. In such images, it’s difficult to locate distinct feature points
* Larger or higher resolution images (more pixels) will allow the extraction of feature points at higher levels of detail, and thus will track better when the camera is closer to the image, or when a higher resolution camera is used

The ARToolKit NFT tracker does not require augmenting the image with Natural Feature Tracking with Fiducial Markers to implement NFT tracking. But, for increased efficiency and robustness, fiducial markers can be used along with NFT markers as part of the dataset when using the NFT tracker.

Fiducial Markers: pattern and barcode markers (also hiro ones).

**Comment by kalwalt** [comment]
Yes this is very important.  Above all the type of image to be tracked is crucial for doing NFT markers. 
In particular the second point is very important. We should do some examples: one bad that is diffcult to be recognized, one medium and the Top example which is the best possible.

**Comment by Carnaux** [comment]
I will look into those limitations.

**Comment by Carnaux** [comment]
- file has to have .jpg extension
 - file name has to contain .jpg extension (e.g. on Mac verify that extension is present)

The node app:
`
let imagePath = glob.sync(srcTest +'/**/*.{jpg,JPG,jpeg,JPEG}', {});
`

It only gets an image if it is a .jpg type, so it already verifies file extension. 

Browser version:
Added verification on file input. The code exits if it is not a .jpg/.jpeg file.

Also, the .min.js will log if it is another file format.

**Comment by Carnaux** [comment]
- I have used a black and white image, set NC=1, but does not work (generates .iset files but not recognized). Someone can try this too? Maybe can be something on the NFT app side, maybe missing some parameters.

Added the `detectColorSpace()` function to the browser version and the node app. I tested and it works( tested the marker creation and marker recognition).

**Comment by Carnaux** [comment]
- after resizing the image (e.g. Using Mac OS Preview tool) the system gives an error 

@nicolocarpignoli  Can you post a log about it?

**Comment by Carnaux** [comment]
- file has to have .jpg extension

Added PNG support for node app and browser.

**Comment by Carnaux** [comment]
Found one more restriction in node app:

Images with width and/or height with 3000px+ generate error:
`TypeError: Cannot read property '0' of undefined`

The decoding library used runs out of memory: 
`Allocation failed - JavaScript heap out of memory`

**Comment by nicolocarpignoli** [comment]
> Found one more restriction in node app:
> 
> Images with width and/or height with 3000px+ generate error:
> `TypeError: Cannot read property '0' of undefined`
> 
> The decoding library used runs out of memory:
> `Allocation failed - JavaScript heap out of memory`
> 
> The browser did generate, but it took 40 min.

in the meantime, we can catch this error with try/catch and log this very thread (like " look at issue #11 on repository" with URL). At least we will avoid new issues raising for the same problem.

**Comment by nicolocarpignoli** [comment]
PNG support seems to work as it does not give error on the node app side, but when I use the descriptors the image is not recognised. 

Anyone has been able to make PNG image work?

**Comment by kalwalt** [comment]
i didn't tried but which image do you useD to test ( width, height )?

**Comment by Carnaux** [comment]
I tested now with this [image](http://www.clker.com/clipart-49739.html) and this [example](https://github.com/kalwalt/jsartoolkit5/blob/fixing-nft/examples/nft_improved_worker/main_threejs_worker.html) from the fixing-nft branch, and it works.

**Comment by nicolocarpignoli** [comment]
it's working yes, we have to keep in mind that width, height and dpi has to be changed also on fixing-nft (jsartoolkit5) files, where NFT data are loaded.

**Comment by Carnaux** [comment]
Sorry, I didn't understand, change width, height and dpi on the example?

**Comment by nicolocarpignoli** [comment]
see here: https://github.com/kalwalt/jsartoolkit5/blob/fixing-nft/examples/nft_improved_worker/threejs_worker.js#L6

but honestly, my test was not robust. Have to run a more robust test to see if those data are required to be adapted and used.

@Carnaux if you have not changed them, and your image has different width/height/DPI than the pinball one, I guess those parameters are not mandatory.

**Comment by Carnaux** [comment]
I see now! Sorry :smile: I didnt change them, just the URL. I believe they are just to position, scale and draw a 3d object on top of the marker image

**Comment by aliu292** [comment]
I found another constraint, it seems like it needs to be RGB form not CMYK,
