### ISSUE TITLE
Buf is not defined

### ISSUE THREAD

**Issue by jonasjohansson** [Carnaux/NFT-Marker-Creator#12]
1. Cloned repo
2. Ran npm install
3. Ran node app.js

Received error:

```
ReferenceError: buf is not defined
    at Object.<anonymous> (/Users/jonas/Documents/GitHub/NFT-Marker-Creator/app.js:34:12)
```

npm 6.13.2
node 12.13.1

Had a quick look at app.js and seems to be a typo on line 34:

`useJPG(buf);`

buf, should be buff. Runs now. Was there an intention with the "buf"?

**Comment by nicolocarpignoli** [comment]
it was clearly a typo, created a trivial PR to fix this
