### ISSUE TITLE
Developing a desktop app with electron

### ISSUE THREAD

**Issue by kalwalt** [Carnaux/NFT-Marker-Creator#23]
@Carnaux @nicolocarpignoli At this time we can use the app as a command line tool and in a browser with https://carnaux.github.io/NFT-Marker-Creator-Web/ but what about developing a desktop app based on [electron](https://electronjs.org/) ? or with another framework?

**Comment by nicolocarpignoli** [comment]
Honestly I don't see any point in developing a desktop software for that.
In my opinion a web app is usable from both mobile and desktop. But this kind of app will be launched mostly on desktop,from browser. If someone wants to have more control, like developers, and see debug logs or use more options, it's possible to use the node app from terminal. This is my opinion not a choice 😁

**Comment by kalwalt** [comment]
ok maybe i will do it as my personal project, but maybe we can improve a bit the browser version, In this sense i would like to help.

**Comment by nicolocarpignoli** [comment]
I will also help to improve the browser version. It will likely be the preferred one for users.
I will open an issue for that

**Comment by kalwalt** [comment]
note that for an electron app it is all ready with the browser version, I could develop a parallel project with the https://github.com/Carnaux/NFT-Marker-Creator as a git submodule

**Comment by Carnaux** [comment]
The browser version needs a better design, that is responsive and prettier, I got stuck with other project(the plane detection) and forgot to enhance it, sorry. But to build an electron app we can use any of the marker creators, the node or the browser versions, they can be easily adapted, because an electron app is already a static page with node support.

**Comment by kalwalt** [comment]
@Carnaux no problem at all !! Yes we should enhance it, Interesting your project on plane detection! 
As i said if i can i am happy to help and contribute, 
Anyway an electron app is based on Chromium so if the browser version works it will work also the electron app...
