### ISSUE TITLE
Web app version

### ISSUE THREAD

**Issue by nicolocarpignoli** [Carnaux/NFT-Marker-Creator#24]
I think  a good enhancement will be to have a good web app version.

Now the node app version works very good with PNG and JPEG, but many users will likely use the browser one (like the Marker generator for pattern marker of AR.js).

I'd like to open this discussion to understand:

- where is the source code of the web app version? we should include it on the master branch
- how can we make it better?

**Comment by kalwalt** [comment]
@nicolocarpignoli  the source code for the Web version is here https://github.com/Carnaux/NFT-Marker-Creator-Web

**Comment by nicolocarpignoli** [comment]
Ok i'm going to port the web version inside this repo to have them on the same project (they are the same thing but with different interface, basically). And i'm going to enhance design a bit.
