### ISSUE TITLE
Enhance node version

### ISSUE THREAD

**Issue by nicolocarpignoli** [Carnaux/NFT-Marker-Creator#25]
The node version is very good, but I think that the input/output configuration can be better. Actually, to have two folders and place the image in one is ok but can be annoying, also provided the limitation of having just one image on the input folder.

A little improvement, that in my opinion can enhance the user interaction on the node app and makes it more flexible, would be to use command line parameters to specify the input image path and output directory path.
This will be much similar to the majority of terminal scripts UI on which users are comfortable with.

Something like:

`node app.js -i inputImage.png -o output -..... other options` 

where output is a new directory containing the three, generated files (if directory is not present, create it on the fly).

**Comment by Carnaux** [comment]
Got it, I will change it!

**Comment by kalwalt** [comment]
@nicolocarpignoli yes these are preferable options!

**Comment by Carnaux** [comment]
Updated!
