### ISSUE TITLE
Wasm version of NFT-Marker-Creator

### ISSUE THREAD

**Issue by kalwalt** [Carnaux/NFT-Marker-Creator#34]
It would be interesting to try a wasm version of the app (node and web). In theory It shouldn't be too difficult but of course we have to test it.

**Comment by Carnaux** [comment]
Using just wasm?

**Comment by kalwalt** [comment]
> Using just wasm?

I need to understand this, but i think we should do something already done for the WASM version of jsartoolkit5.
