### ISSUE TITLE
Feature request: detecting the confidence level at startup on node app.

### ISSUE THREAD

**Issue by kalwalt** [Carnaux/NFT-Marker-Creator#39]
Actually you can know the confidence level when you finish the marker generation routine. It would be very useful to know in advance at the beginning of the process or with a dedicated command?

**Comment by Carnaux** [comment]
Sorry for taking sooooo long to answer. Yes, it can be easily done. I will update it soon!

**Comment by kalwalt** [comment]
No problem! Thank you!

**Comment by Carnaux** [comment]
@kalwalt Added!

**Comment by kalwalt** [comment]
Perfect! i will test it. :slightly_smiling_face: :iphone:

**Comment by kalwalt** [comment]
Tested see my comment https://github.com/Carnaux/NFT-Marker-Creator/issues/42#issuecomment-613946168
