### ISSUE TITLE
display featureset

### ISSUE THREAD

**Issue by daiyadove** [Carnaux/NFT-Marker-Creator#43]
Hi

I want the `dispFeatureSet` feature

> dispFeatureSet displays trained NFT datasets by overlaying representations of the data points on the source images.

It's a good reference when trying to create a good marker image

**Comment by kalwalt** [comment]
HI @daiyadove i'm working on this feature in another project https://github.com/kalwalt/FeatureSET-Display It is not finished yet, i hope that it will be soon.

**Comment by daiyadove** [comment]
HI @kalwalt Thank you for the information.

I'm waiting for it to be finished! Good luck!
