### ISSUE TITLE
Marker Quality

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#44]
@kalwalt  @nicolocarpignoli ThorstenBux So, I was testing with some images of packagings and with the NFT-Marker-Creator it generated ok, found the features, but it didn't track at all, but with the original GenTexData.exe, it works fine, so the quality of the markers generate by this generator are not equal to the original software. Any idea why? @kalwalt I believe we can use your marker visualization tool to compare them.

**Comment by Carnaux** [comment]
Figured it out! It was the dpi settings! By using 72 as default we use the minimum allowed, but not the natural maximum of the image, so it doesn't use all resolutions possible.

**Comment by kalwalt** [comment]
@Carnaux yes if you set a low dpi value it will have of course a low quantity of descriptors, so ti will be difficult to be detected and tracked. Unfortunately my https://github.com/kalwalt/FeatureSET-Display is not yet ready, i can't visualize the imageSet but i hope to fix this soon...

**Comment by Carnaux** [comment]
Yes, I'm now trying to write some code to detect the dpi based on some info of the image. The EXIF readers are too inconsistent, they read a different thing in different attributes 😞

**Comment by kalwalt** [comment]
Artoolkit lib itself has is own Jpeg readers functions, maybe works better?

**Comment by Carnaux** [comment]
It is a good idea, i will add some testing to my to-do list. I'm still getting better results with the original .exe, even when i use similar dpi values.

**Comment by kalwalt** [comment]
In jpeg.c you can find some function for reading/writing jpeg:
https://github.com/artoolkitx/artoolkit5/blob/master/lib/SRC/AR2/jpeg.c
it is based on jpeglib, emscripten has included it.
