### ISSUE TITLE
How to design markers to have more accuracy ?

### ISSUE THREAD

**Issue by nukadelic** [Carnaux/NFT-Marker-Creator#45]
I have the following marker 
![image](https://user-images.githubusercontent.com/6582633/79622111-1f39e780-8140-11ea-93e9-1c6eabfcaf19.png)
but the confidence level im getting is zero, so i made few more tests and added more entropy at each step, but the confidence level stayed at zero
![image](https://user-images.githubusercontent.com/6582633/79622096-10ebcb80-8140-11ea-9162-20a6a26e7e38.png)
now, i have scaled up the image 300% times, added bunch of noise and distortions to a ridiculous amount, and finally it results in 5 stars confidence
![image](https://user-images.githubusercontent.com/6582633/79622423-6d031f80-8141-11ea-8f1b-edb37835f229.png)

Is there a better way to make markers from vector images ?  

Edit : Using AFrame + AR.JS ( latest versions )

**Comment by Carnaux** [comment]
The first image is as you tried? Same size and all?

**Comment by nukadelic** [comment]
Here are all images in their original size & quality : https://imgur.com/a/DegnzbF

**Comment by Carnaux** [comment]
I tested the original image and it got a value of 0.53 entropy, but it works when I displayed it close to the camera, and when i set the dpi to 100(using the node app), it got a little better.

**Comment by Carnaux** [comment]
The confidence level is going to be reworked soon.
