### ISSUE TITLE
not detecting exif data in image files

### ISSUE THREAD

**Issue by rvigneshw** [Carnaux/NFT-Marker-Creator#46]
D:\LAB\arjs\nft\NFT-Marker-Creator>node app.js -i  /image/cn.jpg
The EXIF info of this image is empty or it does not exist. Do you want to inform its properties manually?

**Comment by Carnaux** [comment]
Unfortunately, the image reader used may not detect the exit but it is an issue with the reader itself. Soon I will add another reader that may work better.
