### ISSUE TITLE
Memory issues when creating two NFTs one after the other

### ISSUE THREAD

**Issue by ThorstenBux** [Carnaux/NFT-Marker-Creator#47]
Hi @Carnaux as mentioned I've created a WS version of your marker creator. Code here: https://github.com/augmentmy-world/NFT-Marker-Creator

Now the issue I'm facing is that if I create two markers one after the other I'm getting
```
[error] Error: unrecognised option '(null)'
RuntimeError: memory access out of bounds
    at wasm-function[373]:0x147ae
    at wasm-function[249]:0xbc17
    at wasm-function[742]:0x2ce93
    at wasm-function[209]:0xa0fa
    at wasm-function[175]:0x7cad
    at wasm-function[118]:0x4ac6
    at wasm-function[893]:0x47067
    at Object.Module._createImageSet (/Users/thorstenbux/repos/2dTracking/nft-marker-creator/nftCreatorWS/libs/NftMarkerCreator_wasm.js:1:106898)
    at runtime (/Users/thorstenbux/repos/2dTracking/nft-marker-creator/nftCreatorWS/create.js:111:12)
    at create (/Users/thorstenbux/repos/2dTracking/nft-marker-creator/nftCreatorWS/create.js:202:5)
```
I've seen this in your original version too if you run the Node version locally and create two marker one after the other you run in a similar issue. Any hint highly appreciated.

**Comment by ThorstenBux** [comment]
found a hack around it you can still see the issue on this branch https://github.com/augmentmy-world/NFT-Marker-Creator/tree/memory-issue

**Comment by Carnaux** [comment]
Strange, I never got a memory issue when creating multiple markers one after another. I will look into it, maybe there are some optimizations I can make.

**Comment by ThorstenBux** [comment]
@Carnaux did you find anything?

On another note. Can it be that all artifacts are linked and use the same name to reference each other? I'm getting this strange error on NFTs which I created using the WebService:
```
[Warning] [info] Reading /markerNFT_0.fset3 (artoolkit_wasm.js, line 1)
[Warning] [error] Error loading KPM data: error reading data. (artoolkit_wasm.js, line 1)
[Warning] [error] Error reading KPM data from /markerNFT_0.fset3 (artoolkit_wasm.js, line 1)
[Warning] [error] ARToolKitJS(): Unable to set up NFT marker. (artoolkit_wasm.js, line 1)
```

Any hints highly appreciated.

**Comment by Carnaux** [comment]
Unfortunately no, i tried generated a bunch of markers one after another, but no errors. The source code is in the Dev branch.

**Comment by Carnaux** [comment]
Maybe the AWS server provides less memory for processes than required?

**Comment by ThorstenBux** [comment]
Thanks, I’m not on aws so that is not it. Memory issues happen locally as well. I can probably share a screenshot the next time I run into that.

The naming issue I shared as well is more troubling right now.

**Comment by Carnaux** [comment]
@ThorstenBux I was getting a similar error when developing the .zft implementation. It was the file content, the cause was the conversion of the compressed data to the original binary data, so it must be something like that. 

What happened to me was: the .fset3 was filled with a uint8 array of a string, and not the real uint8 data, when I tried to load it I got a memory issue.

And the error of reading the .fset3 was when the data was in the correct format, but the content means nothing.

**Comment by ThorstenBux** [comment]
Thanks @Carnaux I think I got a lead regarding the error. 
```[Warning] [info] Reading /markerNFT_0.fset3 (artoolkit_wasm.js, line 1)
[Warning] [error] Error loading KPM data: error reading data. (artoolkit_wasm.js, line 1)
[Warning] [error] Error reading KPM data from /markerNFT_0.fset3 (artoolkit_wasm.js, line 1)
[Warning] [error] ARToolKitJS(): Unable to set up NFT marker. (artoolkit_wasm.js, line 1)```

It might be that it isn't reading the temp asa.xxx files correctly. Do you know where these are created during runtime? Can I potentially change the name and path where they are created using a parameter?

Thanks so much for your support.

**Comment by Carnaux** [comment]
These files are created by the c code and are stored in the emscripten file system. [Here](https://github.com/Carnaux/NFT-Marker-Creator/blob/dev/emscripten/assemble.c) one of the first line is the filename variable.

**Comment by ThorstenBux** [comment]
Yes I know but I can’t see them during runtime and whenever I run it in an ExpressJS environment the created markers are not useable 😔. Thought maybe that is a lead. 

Do you think you could have a look at the WS code?

**Comment by ThorstenBux** [comment]
Hi @Carnaux I found the issue with creating the marker. My bad. When I sent the uint8 array over the wire it got broken. It is working now.

I'll keep you posted on the memory issue if I encounter it again.

I also wonder what might happen in a server scenario if the wasm part is being called several times at the same time. Guess I need to set up some stress tests.

**Comment by Carnaux** [comment]
Nice!! We were in the right lead. That is a good test to do if it is a dedicated server it should handle a good number.

**Comment by shubhamraghav1** [comment]
hi @ThorstenBux how did u resolve this error:
[Warning] [error] Error loading KPM data: error reading data. (artoolkit_wasm.js, line 1)
[Warning] [error] Error reading KPM data from /markerNFT_0.fset3 (artoolkit_wasm.js, line 1)
[Warning] [error] ARToolKitJS(): Unable to set up NFT marker. (artoolkit_wasm.js, line 1)
