### ISSUE TITLE
Is there a way to create the nft markers in native app, using opencv or similar lib?

### ISSUE THREAD

**Issue by TheBricktop** [Carnaux/NFT-Marker-Creator#49]
NFT tracker creator is pretty slow at the moment and prone to hangups when the image is not too good or is too big . 
What is the description method for creating the nft markers? Is it creating some king of lookup table to speed up recognition?
Is there a way to use other libraries (like opencv or accord.net) to create similar files compatible  with ar.js?

**Comment by Carnaux** [comment]
Unfortunately no, the only other software that I know is the [genTexData.exe](https://github.com/artoolkitx/arunity5/blob/master/bin/genTexData.exe) (Works only on Windows), and the NFT-Creator is a node/web porting of that code. Give the [source code](https://github.com/Carnaux/NFT-Marker-Creator/blob/dev/emscripten/assemble.c) a look, maybe we can figure out some optimization.
