### ISSUE TITLE
cannot process image

### ISSUE THREAD

**Issue by Azleal** [Carnaux/NFT-Marker-Creator#51]
hi @Carnaux,  there are some problems when processing images with .jpg or jpeg extension.
 
1. clone project
2. `npm install`  (node version 13.4.0)
3. copy `https://raw.githubusercontent.com/AR-js-org/AR.js/master/aframe/examples/image-tracking/nft/trex-image-big.jpeg` to root folder of the project
4. `node app.js -i trex-image-big.jpeg`

after executing this, it says: TypeError: Cannot read property '0' of undefined
![image](https://user-images.githubusercontent.com/7901126/83528556-d4233a80-a51b-11ea-9fcd-1f774051eb2f.png)

however, if i use the web version of marker creator with the same image, it works~

**Comment by kalwalt** [comment]
@Azleal it seems strange to me. maybe an issue with the name of the file? can you try to rename the file and remove all the `-` chars?

**Comment by Carnaux** [comment]
It's something with the image reader, it cannot read some jpg encodings, but if you open the image on Paint, Gimp, Photoshop(any image editing software), and "Save as" it probable that it will work. This is already on my to do list.

**Comment by Azleal** [comment]
> @Azleal it seems strange to me. maybe an issue with the name of the file? can you try to rename the file and remove all the `-` chars?

hi @kalwalt, thanks for your reply, it's strange to me too😄. and I already tried to change the file name to dragon.jpeg, it still does't work.

**Comment by Azleal** [comment]
> It's something with the image reader, it cannot read some jpg encodings, but if you open the image on Paint, Gimp, Photoshop(any image editing software), and "Save as" probably will work. This is already on my to do list.

@Carnaux, thanks for your reply, it worked by using your method. after save as a png image, the error message didn't show up anymore. 

however, I've tried several different images, and the confidence level either 0/5 or NaN/5. let's take the dragon image as an example, if I use the web version to generate, the confidence is 3/5.

should I open another issue for this?

**Comment by Carnaux** [comment]
That is another thing I'm working on, the confidence level is really inconsistent, that means that your 0/5 images may still work. I hope the new one will be better. Sorry for all inconvenience 😞
