### ISSUE TITLE
RuntimeError: abort(undefined) at Error

### ISSUE THREAD

**Issue by Dryra** [Carnaux/NFT-Marker-Creator#55]
Hello, 
Thank you very much for this tool!

I'm having issues creating FeatureSet files using the nodejs variant, the conversion is working up until these lines:
Saving FeatureSet...
[info]   Done.
[info] Generating FeatureSet3...
[info] (4961, 7023) 300.000000[dpi]

Then it crashes with stacktrace: 

> Assertion `mData.get()` failed in C:\wamp64\www\emscripten\emsdk\NFT-Marker-Creator-dev\emscripten\artoolkit5\lib\SRC\KPM\FreakMatcher\framework\image.cpp line 149: Data pointer is NULL
> undefined
> undefined
> RuntimeError: abort(undefined) at Error
>     at jsStackTrace (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:23770)
>     at stackTrace (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:23941)
>     at abort (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:20844)
>     at _abort (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:85471)
>     at wasm-function[362]:373
>     at wasm-function[1068]:162
>     at wasm-function[1161]:51
>     at wasm-function[1059]:127
>     at wasm-function[1061]:207
>     at wasm-function[1048]:67
> RuntimeError: abort(undefined) at Error
>     at jsStackTrace (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:23770)
>     at stackTrace (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:23941)
>     at abort (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:20844)
>     at _abort (C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1:85471)
>     at wasm-function[362]:373
>     at wasm-function[1068]:162
>     at wasm-function[1161]:51
>     at wasm-function[1059]:127
>     at wasm-function[1061]:207
>     at wasm-function[1048]:67
> C:\WebAR\NFT-Marker-Creator\libs\NftMarkerCreator_wasm.js:1
> var Module=typeof Module!=="undefined"?Module:{};var scope;if(typeof window!=="undefined"){scope=window}else if(typeof window=="undefined"){scope=global}else{scope=global}if(scope.artoo
> lkit_wasm_url){var downloadWasm=function(url){return new Promise(function(resolve,reject){var wasmXHR=new XMLHttpRequest;wasmXHR.open("GET",url,true);wasmXHR.responseType="arraybuffer";
> wasmXHR.onload=function(){resolve(wasmXHR.response)};wasmXHR.onerror=function(){reject("error "+wasmXHR.status)};wasmXHR.send(null)})};var wasm=downloadWasm(scope.artoolkit_wasm_url);Mo
> dule.instantiateWasm=function(imports,successCallback){console.log("instantiateWasm: instantiating synchronously");wasm.then(function(wasmBinary){console.log("wasm download finished, be
> gin instantiating");var wasmInstantiate=WebAssembly.instantiate(new Uint8Array(wasmBinary),imports).then(function(output){console.log("wasm instantiation succeeded");successCallback(out
> put.instance)}).catch(function(e){con
> 

What I do not quite understand is this line: 

`C:\wamp64\www\emscripten\emsdk\NFT-Marker-Creator-dev\emscripten\artoolkit5\lib\SRC\KPM\FreakMatcher\framework\image.cpp line 149` 

as I don't have that folder on my machine.

Image type: jpg or png
Image Width 4961px
Image Height: 7023px
DPI: 300dpi

Any help is appreciated. Thank you!

**Comment by Carnaux** [comment]
Hey, sorry for taking a long time to answer :/ That's a new error for me, I will look into it. Can you send me the image you're using?

**Comment by Dryra** [comment]
Hello, no problem!
I will send  the image to your email.

Thank you for your help!

**Comment by Carnaux** [comment]
Got the same error using 72dpi, I will look into it!

**Comment by Carnaux** [comment]
If possible, check the new update, it should fix that.
