### ISSUE TITLE
ImageSet generation error

### ISSUE THREAD

**Issue by allestaire** [Carnaux/NFT-Marker-Creator#58]
There was an error upon running the command it says that `writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!` but when I change `writeStringToMemory ` to `stringToUTF8` I got other errors `'stringToUTF8' was not exported`

**Comment by Carnaux** [comment]
The code structure has to change a bit to use 'stringToUTF8', thats why I didn't change it yet.
