### ISSUE TITLE
RuntimeError when trying to process a '.jpg' file (node version)

### ISSUE THREAD

**Issue by stevenjmarsh** [Carnaux/NFT-Marker-Creator#59]
Hello, and thank you for providing this very useful tool!

I have been able to successfully use the web version of NFT-Marker-Creator to process both '.png' and '.jpg' files.
I can also successfully generate descriptor files from '.png' files with the node version. (NOTE: I have not been able successfully recognize the image for any .png file I've created descriptor files for)

However, I am unable to process '.jpg' files with the node version. I get a RuntimeError.
Here is the image: https://avo-content-dev.s3.amazonaws.com/image-tracking-proto.jpg
(I did try a different .jpg file, which fails as well)

Note this image succeeds when using the web version, but fails with the node version.

I followed the 'How to use it' steps in the README, to install and run the node version.

Here is the error...

### Output 
```
[13:29:07] smarsh:NFT-Marker-Creator git:(test-run*) $ node app.js -i greenlight.jpg -noConf -noDemo
Check output path: /Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/output/

TypeError: Cannot read property '0' of undefined
```

I stepped through the application in the debugger, and at line 221 in `app.js`, the call to `inkjet.decode()` returns an error.

I noticed there is a new version of the inkjet package available. I tried that version of the package, and still get a failure. The output is different however.

### Output when using npm package inkjet v3.0.0
```
[13:17:24] smarsh:NFT-Marker-Creator git:(test-run*) $ node app.js -i greenlight.jpg -noConf -noDemo
Check output path: /Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/output/
TypeError: Cannot read property 'value' of undefined
TypeError: Cannot read property 'value' of undefined
/Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1
var Module=typeof Module!=="undefined"?Module:{};var scope;if(typeof window!=="undefined"){scope=window}else if...


RuntimeError: abort(TypeError: Cannot read property 'value' of undefined) at Error
    at jsStackTrace (/Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:23770)
    at stackTrace (/Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:23941)
    at process.abort (/Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:20844)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
    at process.abort (/Users/smarsh/dev_projects/source/reference-projects/NFT-Marker-Creator/libs/NftMarkerCreator_wasm.js:1:20875)
    at process.emit (events.js:314:20)
    at processPromiseRejections (internal/process/promises.js:245:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

Any suggestions for fixes, or settings for me to try, are greatly appreciated! Thanks.

**Comment by kalwalt** [comment]
Hi @stevenjmarsh very weird error! At the moment i have no idea, maybe you can try to remove the exif data (in the image) and try to save again the image. I know that someone had this similar issue with the [NFT-creator-WS](https://github.com/webarkit/NFT-Creator-WS) made by @ThorstenBux. Maybe he can help in someway.

**Comment by stevenjmarsh** [comment]
Thanks, I will give that a try.

**Comment by ThorstenBux** [comment]
If you just need a single trackable aka marker you can use this http://nftcreator.tripod-digital.co.nz/

**Comment by ThorstenBux** [comment]
Otherwise I can also support if you find issues on the Webserver version

**Comment by stevenjmarsh** [comment]
Thanks @ThorstenBux . I am trying to automate generating the NFT descriptor files, so the node version seems like the best fit at this point. If I do see a need to use the Webserver version in this case and need help, will let you know. Thanks!!

**Comment by ThorstenBux** [comment]
As a matter of fact I already do that 😊 in a pro version. If you are working on a commercial product and would like to have support or access to the pro version, let me know.

Kind regards
Thorsten Bux

Sent from my iPhone

On 7/10/2020, at 9:03 AM, Steve Marsh <notifications@github.com> wrote:

﻿

Thanks @ThorstenBux<https://eur06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FThorstenBux&data=02%7C01%7C%7C10f332608d2f463b47f408d86a32ed85%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637376114243672490&sdata=HUjAlfHHN4ggBO27IjBT6WUxyTCucZwWwKI4X6K%2FmDQ%3D&reserved=0> . I am trying to automate generating the NFT descriptor files, so the node version seems like the best fit at this point. If I do see a need to use the Webserver version in this case and need help, will let you know. Thanks!!

**Comment by stevenjmarsh** [comment]
@ThorstenBux , @kalwalt  When using the node version, I was able to successfully generate descriptor files from a .png image. However, the image is not recognized.  I've tried the 'npm run demo', as well as an Image recognition app I wrote that works when using descriptor files generated from the Web version.

So, ultimately, I'm not able to successfully use the node version with jpg or png files. jpg files crash the node process. png files generate descriptor files, but the image is not recognized.

Do you know if the latest node version works? I want to determine if I am doing something incorrectly, or am using poor images. Thanks.

**Comment by kalwalt** [comment]
> So, ultimately, I'm not able to successfully use the node version with jpg or png files. jpg files crash the node process. png files generate descriptor files, but the image is not recognized.

I will try to create the descriptors from the image you provided in the first comment. Can't say so much at the moment,

> Do you know if the latest node version works? I want to determine if I am doing something incorrectly, or am using poor images.

I think yes, it should work but maybe @Carnaux  can say something more. I don't think you are using a poor image.

**Comment by juliangoacher** [comment]
I had this problem after editing a jpeg using Preview on MacOS, was able to get around it by opening and saving the image from a different image editor (e.g. Gimp).

**Comment by Cocktails0921** [comment]
I have got the error such as the following image when generate from jpg file to NTF using node generate.
![Capture](https://user-images.githubusercontent.com/58881761/98302695-d7a17d00-1ff7-11eb-84fb-b6d00dada84e.PNG)
please let me know why this error happen.
png file generate to NTF is perfect, but jpg file generate has some issue, i think.

**Comment by ragavendranbala** [comment]
#64
