### ISSUE TITLE
Confidence level not calculating

### ISSUE THREAD

**Issue by Sk031397** [Carnaux/NFT-Marker-Creator#61]
I am trying to calculate the confidence level for a small png file, I have tried using the online generator as well as node version but both have outputted all my images as 0 confidence unless I manipulate the shannon entropy

**Comment by ragavendranbala** [comment]
@Sk031397 How to manuplate that entropy? any docs available?

**Comment by Carnaux** [comment]
Yeah, the current confidence level is based on image entropy, but that didn't work :/ I'm working on a new one.
