### ISSUE TITLE
QR Images are not working

### ISSUE THREAD

**Issue by ragavendranbala** [Carnaux/NFT-Marker-Creator#62]
Tied creating NFT marker using a genrated QR code, it showing the confidence level as 0 star. But the Same QR having 5 star Rating on Vuforia's Image target creator. Kindly help me to create the QR as NFT marker. Thanks in advance

![Screenshot 2020-11-22 155928](https://user-images.githubusercontent.com/32410475/99901463-f3d23900-2cdc-11eb-8bbd-e95fad3c2445.png)
![Screenshot 2020-11-22 155912](https://user-images.githubusercontent.com/32410475/99901464-f5036600-2cdc-11eb-8a54-06e916a525fd.png)

**Comment by Carnaux** [comment]
The current confidence level isn't the best, I'm working on a new one.
