### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by wys050311** [Carnaux/NFT-Marker-Creator#63]
![158 OP 89UQ0P4TU@EF(GCC](https://user-images.githubusercontent.com/54499428/100841411-36043300-34b2-11eb-9f52-51bf60770eb7.png)

**Comment by ragavendranbala** [comment]
Kindly check PR #64

**Comment by Carnaux** [comment]
The new update with the changes made by @ragavendranbala should fix that, if still happening let me know.
