### ISSUE TITLE
More information about the parameters ( level / leveli )

### ISSUE THREAD

**Issue by Makio64** [Carnaux/NFT-Marker-Creator#65]
Hi,

the documentation for getting started is great but some paramaters are really dark to me like level and leveli ?

I would love to have more information about what they are doing, thanks!

the most dark parameters : 

```
-level=n
     (n is an integer in range 0 (few) to 4 (many). Default 2.'
-sd_thresh=<sd_thresh>
-max_thresh=<max_thresh>
-min_thresh=<min_thresh>
-leveli=n
     (n is an integer in range 0 (few) to 3 (many). Default 1.'
-max_dpi=<max_dpi>
-min_dpi=<min_dpi>

```

**Comment by williamqian** [comment]
I agree too

**Comment by Carnaux** [comment]
I will add descriptions to the flags in a new update soon.

**Comment by jwagsters** [comment]
Did the descriptions ever get added?  I'm searching all over the place for them, but I can't find them anywhere.
