### ISSUE TITLE
duplicate url with jsartoolkit5

### ISSUE THREAD

**Issue by dolgong2** [Carnaux/NFT-Marker-Creator#68]
Trying to use both NftMarkerCreator and jsartoolkt5 in a single web page. 

both project need to specify wasm url like 
<script type='text/javascript'>
          var artoolkit_wasm_url = './lib/NftMarkerCreator_wasm.wasm';
</script>

<script type='text/javascript'>
      var artoolkit_wasm_url = '../build/artoolkit_wasm.wasm';
</script>

Error on console 
Uncaught RangeError: Maximum call stack size exceeded

**Comment by Carnaux** [comment]
You will need to compile both into one file using emscriten, use the nft-marker-creator dev branch as template.
