### ISSUE TITLE
the fset/iset files created from web are different from node

### ISSUE THREAD

**Issue by lukemcredmond** [Carnaux/NFT-Marker-Creator#71]
Hi Guys

looking for any assistance, 

i tried running the node.js application and provide it with a png left arguments at the default.
it produced 3 files but when i run them in the demo they are not be detected.

i then provided the same png to the website replaced the nodejs generated fset/iset files with the ones from the website and they are been detected.

please see attached, the nodejs ones are a different size than the website ones.
i am not sure if i should be passing in any addtional args etc

[output.zip](https://github.com/Carnaux/NFT-Marker-Creator/files/6213049/output.zip)

**Comment by Carnaux** [comment]
Hey, yeah, i've noticed that, i suspect that is a memory management issue. I will look into that in the future
