### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by NANICYB** [Carnaux/NFT-Marker-Creator#73]
Hi carnaux, I have error while I run the command you gave. How could I resolve this?

**Comment by Carnaux** [comment]
Which command and which error?

**Comment by cybersera** [comment]
> Which command and which error?
node app.js -i PATH/TO/IMAGE

**Comment by cybersera** [comment]
> Which command and which error?

![IMG_20210420_080910](https://user-images.githubusercontent.com/59509865/115329317-c4eac100-a1af-11eb-9c07-65d86cde9d8a.jpg)

**Comment by Carnaux** [comment]
Did you re-run 'npm install'? That should fix it.

**Comment by cybersera** [comment]
Yes

**Comment by cybersera** [comment]
could you send any video that with step by step plz?

**Comment by Carnaux** [comment]
The only way I was able to get a similar error is to remove that library from the node_modules folder, but it was solved by deleting the folder and running "npm install" again.
