### ISSUE TITLE
Documentation of the advanced options

### ISSUE THREAD

**Issue by jonnypage** [Carnaux/NFT-Marker-Creator#74]
I was wondering if we could get a brief rundown on what each of the advanced options does, I'd love to play around with them but I have no idea what each of them does.

Thanks!

**Comment by Carnaux** [comment]
Hi! I'm planning to release a more complete description of them in the next week or some time soon.

**Comment by jwagsters** [comment]
Please, please, please do this!  Even if it's not super-detailed documentation, a few paragraphs would really help to get a better idea of what is happening when flags and settings are changed.

**Comment by RepSklvska** [comment]
So where can I see that description now? Much grateful if I can read it
