### ISSUE TITLE
NFT marker creator web version does not display confidence level

### ISSUE THREAD

**Issue by jang038** [Carnaux/NFT-Marker-Creator#76]
The new revised NFT marker creator on web does not show the confidence level of image before conversion. Is it possible to add it in so we can ensure our images are good before converting?

**Comment by scaleupjordan** [comment]
Yes!! This is very confusing as the new options are not being explained. Will there be documentation coming up on how to assess the confidence level?

**Comment by jrDev1** [comment]
Would like an update to this too please!

Thanks,
jrDev

**Comment by Carnaux** [comment]
Hi! I'm developing a more reliable confidence level, soon i will add more documentation and features!
