### ISSUE TITLE
Setting to change tracking tolerance?

### ISSUE THREAD

**Issue by taime** [Carnaux/NFT-Marker-Creator#79]
Is there any setting, that change tolerance of image recognition?
I want to setup better image recognition even if it cause a lot false positive triggering recognition...
**Look at the video with example of problem.**

https://user-images.githubusercontent.com/1723871/122280059-73318f00-cef1-11eb-8736-2a464421380f.MP4

Is it possible?

**Comment by Carnaux** [comment]
Hey, yeah, you can create a marker with more density and with more levels, check out the flags on the node app, for now, there is no description about them(i will add, but I don't know when), but you can try to read the code to get some ideia, also you can change jsartoolkit5 configurations and build a custom one with some config changes so you can track with steeper angles.
