### ISSUE TITLE
Use of EXIF-JS and errors

### ISSUE THREAD

**Issue by Carnaux** [Carnaux/NFT-Marker-Creator#8]
Using the code to read jpeg headers from https://github.com/exif-js/exif-js is possible to get all properties listed in #6.

Problems detected:

1. Not all jpg can be read by the library, so it is needed to create default values for them.
2. The ones that can be read, give the error "Empty JPEG image (DNL not supported)"  during the creation of the .iset file. 

Maybe related with 2:
 https://stackoverflow.com/questions/16470268/empty-jpeg-image-dnl-not-supported-node-canvas

https://github.com/KhronosGroup/WebGL/issues/1533

**Comment by Carnaux** [comment]
Possible fix: https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/structure.txt

**Comment by samsgates** [comment]
same issue :

![image](https://user-images.githubusercontent.com/4558944/68121197-27ed8700-ff2d-11e9-9f11-f2bd6f661210.png)

let me know how to proceed further

**Comment by nicolocarpignoli** [comment]
Is this fixed? 😁
