### ISSUE TITLE
SOLVED: What are good settings?

### ISSUE THREAD

**Issue by SwaggerNiels** [Carnaux/NFT-Marker-Creator#89]
- starting from the examples in https://github.com/webarkit/ARnft/tree/master/examples
- using the pinball.jpg everything works.

I use NFT creator (web/node.js) and use a high confidence picture.
- upload the 3 files directly to a folder of ARnft (examples/DataNFT)
- replace the path in one of the examples with my own
- and check if i can detect it

It detects it as outputted in the console but then it does not show the red cube, flamingo, etc.
What could be the problem here?

**Comment by SwaggerNiels** [comment]
Found how to get these markers to work:
Just set the change the app.js script all dpi default values: "72" to "120"
and run it on a picture that actually has 120 dpi (you can use ctrl-R in paint.net to set the dpi/pixels-per-inch to 120)
used this command:
node .\app.js -i .\my_image.jpg -dpi=f -max_dpi=120 -min_dpi=20

Now it works!
This took me a long time to figure out though. Its too bad that no one is maintaining these gems...

**Comment by kalwalt** [comment]
@SwaggerNiels i think Daniel @Carnaux is very busy lately and me too, so sometimes we have no time to answer. 
But i suggest to you to use 300 dpi for a NFT marker, if an image doesn't provide a dpi value add it manually in you preferred image editor. 
Daniel created also a wiki page for [Creating-good-markers](https://github.com/Carnaux/NFT-Marker-Creator/wiki/Creating-good-markers)
You can also take a look at [the old docs for making NFT makers](https://kalwalt.github.io/artoolkit-docs/3_Marker_Training/marker_nft_training.html), consider that NFT-Marker_Creator is partially based on genTexData.cpp and so many commnds are similars.
My dream is to collect all these docs in our [webarkit.org](https://www.webarkit.org) website in a future, if we found time and help by other contributors.
Hope that this can help you.

**Comment by SwaggerNiels** [comment]
Indeed the high dpi seemed to work, i just got impatient.
Thank you for replying!
