### ISSUE TITLE
I build a js file. What's next?

### ISSUE THREAD

**Issue by AnastasiiaaaaM** [Carnaux/NFT-Marker-Creator#9]
Greetings! Could you please help me?

I managed to build NftMarkerCreator.min.js, libar.bc and libjpeg.bc files using my Mac. 
What's next? How can I convert JPEG images?

Thanks in advance!

**Comment by kalwalt** [comment]
@AnastasiiaaaaM this app is in an experimental phase/step if you want create your own NFT markers follow these instructions https://github.com/artoolkitx/artoolkitx/wiki/Creating-and-using-NFT-markers

**Comment by nicolocarpignoli** [comment]
@kalwalt only works on windows right now, correct?

**Comment by kalwalt** [comment]
> @kalwalt only works on windows right now, correct?

no as answered in this [comment](https://github.com/Carnaux/NFT-Marker-Creator/issues/6#issuecomment-564026005) i was able to build the ArtoolkitX project and with the **artoolkitx_genTexData** app to make my NFT marker.  You can do also on Mac but you need to install all dependencies, i have no idea if it is better than doing in linux.... but i think for Windows there are ready binaries,

**Comment by kalwalt** [comment]
Try to look at http://www.artoolkitx.org/docs/downloads/ or go to the release page https://github.com/artoolkitx/artoolkitx/releases it should be included in the **artoolkitX.for.Windows.v1.0.zip**

**Comment by kalwalt** [comment]
...and note that genTexData from Artoolkit5 or from ArtoolkitX do the same.
